### ISSUE TITLE
Build failure ‘cl_half2’ ?

### ISSUE THREAD

**Issue by rico666** [ekondis/mixbench#7]
After some promising start - unfortunately...

```
g++ -c -O2 -I/opt/cuda/include -Wall mix_kernels_ocl.cpp -o mix_kernels_ocl.o
mix_kernels_ocl.cpp: In function ‘void runbench(int, cl_command_queue, _cl_kernel* (*)[33], cl_mem, long int, size_t, bool)’:
mix_kernels_ocl.cpp:169:8: error: ‘cl_half2’ does not name a type; did you mean ‘cl_half’?
  const cl_half2 seed_h = {15360, 15360}; // {1.0, 1.0}
        ^~~~~~~~
        cl_half
```

**Comment by ekondis** [comment]
This happens because some opencl headers (older?) do not include a definition for cl_half2 type.

Revert this [commit](https://github.com/ekondis/mixbench/commit/bdd0ea575646fc41b557adc3be81d4b0382b6669#diff-86cc928ff1ea688ae9fa48fe15dd4e1e) which removed these definitions as on other installations a redefinition error was raised.

**Comment by rico666** [comment]
Hm. Happens with the newest Nvidia OpenCL definitions that come with their 387.x driver. I know Nvidia is notoriously known for their novercal OpenCL support. 
https://forums.khronos.org/showthread.php/11388-how-to-use-cl_half2?s=703a6e7bcdf1d54c5522ff86b4fc4ca2&p=37715&viewfull=1#post37715

> This is a bug in the Khronos OpenCL headers. We have this on our internal bug tracking system, so it should be fixed in a future release of the headers.

That was June 2015 - seems not to have proliferated to Nvidia yet.
